// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oacdbxkcyazmovkxlfhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hY2RieGtjeWF6bW92a3hsZmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjI4NzgsImV4cCI6MjA2MTQzODg3OH0.v2mYrFy4fJ1Di5kzCZxnAFs_FXV9Fj8sRKDfLw3BQho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);